CREATE TABLE IF NOT EXISTS sessions (
  id CHAR(36) PRIMARY KEY,
  scenario_id CHAR(36),
  mode ENUM('duel','coop') NOT NULL,
  user_a_id CHAR(36) NULL,
  user_b_id CHAR(36) NULL,
  user_a_role VARCHAR(10),
  user_b_role VARCHAR(10),
  chat_transcript JSON DEFAULT (JSON_ARRAY()),
  user_a_score INT NULL,
  user_b_score INT NULL,
  user_a_ai_feedback JSON NULL,
  user_b_ai_feedback JSON NULL,
  team_score INT NULL,
  team_ai_feedback JSON NULL,
  status ENUM('waiting','in_progress','completed','abandoned') DEFAULT 'waiting',
  started_at TIMESTAMP NULL,
  ended_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE SET NULL,
  FOREIGN KEY (user_a_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (user_b_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_sessions_status (status),
  INDEX idx_sessions_scenario_id (scenario_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
